#!/usr/bin/env python3
"""Clean runtime data generated by local or production Velab runs.

Default mode is dry-run. Pass --execute to delete candidates.
"""

from __future__ import annotations

import argparse
import os
import shutil
import time
from dataclasses import dataclass
from pathlib import Path


BACKEND_ROOT = Path(__file__).resolve().parents[1]
DATA_ROOT = Path(os.environ.get("LOG_PIPELINE_DATA_ROOT", BACKEND_ROOT / "data"))


@dataclass(frozen=True)
class Target:
    path: Path
    label: str


def _age_cutoff(days: int) -> float:
    return time.time() - days * 24 * 60 * 60


def _is_old(path: Path, cutoff: float) -> bool:
    try:
        return path.stat().st_mtime < cutoff
    except OSError:
        return False


def _iter_children(root: Path, cutoff: float):
    if not root.exists():
        return
    for child in root.iterdir():
        if _is_old(child, cutoff):
            yield child


def _delete(path: Path) -> None:
    if path.is_dir():
        shutil.rmtree(path)
    else:
        path.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description="Clean Velab runtime data")
    parser.add_argument("--older-than-days", type=int, default=30, help="minimum age before deletion")
    parser.add_argument("--execute", action="store_true", help="delete files; default is dry-run")
    parser.add_argument("--include-docs", action="store_true", help="also clean uploaded technical documents")
    parser.add_argument("--include-indexes", action="store_true", help="also clean generated indexes")
    args = parser.parse_args()

    if args.older_than_days < 1:
        parser.error("--older-than-days must be >= 1")

    cutoff = _age_cutoff(args.older_than_days)
    targets = [
        Target(DATA_ROOT / "workspaces", "agent workspaces"),
        Target(DATA_ROOT / "uploads", "temporary uploads"),
        Target(DATA_ROOT / "work", "extractor scratch"),
        Target(DATA_ROOT / "bundles", "extracted log bundles"),
    ]
    if args.include_docs:
        targets.append(Target(DATA_ROOT / "docs" / "uploaded", "uploaded technical docs"))
    if args.include_indexes:
        targets.append(Target(DATA_ROOT / "indexes", "generated indexes"))

    candidates: list[Path] = []
    for target in targets:
        for child in _iter_children(target.path, cutoff) or []:
            candidates.append(child)
            print(f"{'DELETE' if args.execute else 'DRY-RUN'} {target.label}: {child}")

    if args.execute:
        for path in candidates:
            _delete(path)

    mode = "deleted" if args.execute else "would delete"
    print(f"Cleanup complete: {mode} {len(candidates)} item(s) under {DATA_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
